# CAMPAIGNS


### Retrieve all campaigns
GET http://localhost:8080/campaigns

### Create new campaign
POST http://localhost:8080/campaigns
Content-Type: application/json

{
  "name": "Campaign 3",
  "description": "The third campaign"
}

> {%
    client.global.set("campaignId", response.body.id);
%}

### Retrieve specific campaign by id
GET http://localhost:8080/campaigns/{{ campaignId }}

### Edit campaign name and description
PUT http://localhost:8080/campaigns/{{ campaignId }}
Content-Type: application/json

{
  "id": {{ campaignId }},
  "name": "Campaign III",
  "description": "The third campaign is edited"
}

### Remove specific campaign by id
DELETE http://localhost:8080/campaigns/{{ campaignId }}


# SESSIONS

### Create new session for campaign
POST http://localhost:8080/sessions
Content-Type: application/json

{
  "campaignId": {{ campaignId }},
  "sessionDate": "2025-10-15"
}

> {%
    client.global.set("sessionId", response.body.id);
%}

### Retrieve all sessions for campaign
GET http://localhost:8080/sessions/byCampaign/{{ campaignId }}

###  Edit session date
PUT http://localhost:8080/sessions/{{ sessionId }}
Content-Type: application/json

{
  "id": {{ sessionId }},
  "campaignId": {{ campaignId }},
  "sessionDate": "2025-10-18"
}

### Remove session
DELETE http://localhost:8080/sessions/{{ sessionId }}


# NOTES

### Create new note for session
POST http://localhost:8080/notes
Content-Type: application/json

{
  "sessionId": {{ sessionId }},
  "content": "They've taken the hobbits to Isengard!",
  "authorName": "Legolas"
}

> {%
    client.global.set("noteId", response.body.id);
%}

### Retrieve specific Note by id
GET http://localhost:8080/notes/{{ noteId }}

### Retrieve all notes for session
GET http://localhost:8080/notes/bySession/{{ sessionId }}

### Edit note content
PUT http://localhost:8080/notes/{{ noteId }}
Content-Type: application/json

{
  "id": {{ noteId }},
  "sessionId": {{ sessionId }},
  "content": "No, wait! The hobbits are behind me.",
  "authorName": "Honey-Boo-Boo"
}

### Remove note
DELETE http://localhost:8080/notes/{{ noteId }}



# MALFORMED REQUESTS

### Creating malformed campaign
POST http://localhost:8080/campaigns
Content-Type: application/json

{
  "description": 5
}

### Malformed campaign: name too long
POST http://localhost:8080/campaigns
Content-Type: application/json

{
  "name": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...",
  "description": "Far too long."
}