### GET All campaigns
GET http://localhost:8080/campaigns

### GET Rat Cellar Heroes
GET http://localhost:8080/campaigns/54e2d203-38dd-4f9a-a67d-dcab8f00952c

###
POST http://localhost:8080/campaigns
Content-Type: application/json

{
  "name": "Campaign 3",
  "description": "The third campaign"
}

> {%
    client.global.set("campaignId", response.body.id);
%}

### GET Campaign 3
GET http://localhost:8080/campaigns/{{ campaignId }}


### DELETE Campaign 3
DELETE http://localhost:8080/campaigns/{{ campaignId }}

### POST New session for campaign
POST http://localhost:8080/sessions
Content-Type: application/json

{
  "campaignId": {{ campaignId }},
  "date": "2025-10-15"
}

### GET All sessions for campaign
GET http://localhost:8080/sessions/byCampaign/{{campaignId}}
